"""
Subjects definition for the Learning Platform.
"""

SUBJECTS_DATA = [
    {
        "name": "Data Structures & Algorithms",
        "slug": "dsa",
        "description": "Master algorithmic thinking, Big-O analysis, memory internals, search patterns, and sorting algorithms in Python.",
        "icon": "Binary",
        "order": 1,
        "difficulty": "Beginner to Advanced",
        "isPublished": True,
        "estimated_hours": "45+ hrs",
    },
    {
        "name": "Machine Learning",
        "slug": "machine-learning",
        "description": "Master statistical learning theory, bias-variance tradeoff, feature scaling, linear regression, evaluation metrics, and ensembles.",
        "icon": "Brain",
        "order": 2,
        "difficulty": "Intermediate",
        "isPublished": True,
        "estimated_hours": "40+ hrs",
    },
    {
        "name": "Python & Data Engineering",
        "slug": "python",
        "description": "Master core Python execution, memory management, shallow vs deep copy, OOP, concurrency, Pandas manipulation, and Git workflows.",
        "icon": "Terminal",
        "order": 3,
        "difficulty": "Beginner to Advanced",
        "isPublished": True,
        "estimated_hours": "35+ hrs",
    },
    {
        "name": "SQL & Relational Databases",
        "slug": "sql",
        "description": "Master relational database architecture, ACID transactions, 1NF to BCNF normalization, query execution order, joins, and window functions.",
        "icon": "Database",
        "order": 4,
        "difficulty": "Beginner to Intermediate",
        "isPublished": True,
        "estimated_hours": "25+ hrs",
    },
    {
        "name": "MongoDB & NoSQL",
        "slug": "mongodb",
        "description": "Learn flexible JSON/BSON document modeling, CRUD querying, indexing strategies, and high-performance aggregation pipelines.",
        "icon": "Layers",
        "order": 5,
        "difficulty": "Beginner to Intermediate",
        "isPublished": True,
        "estimated_hours": "20+ hrs",
    },
    {
        "name": "Large Language Models",
        "slug": "llm",
        "description": "Explore transformer foundations, tokenization, self-attention mechanics (Q, K, V), positional encodings, and decoding strategies.",
        "icon": "Sparkles",
        "order": 6,
        "difficulty": "Intermediate to Advanced",
        "isPublished": True,
        "estimated_hours": "30+ hrs",
    },
    {
        "name": "Generative AI & RAG",
        "slug": "generative-ai",
        "description": "Build production GenAI applications with prompt engineering, vector search, embeddings, and end-to-end RAG pipelines.",
        "icon": "Wand2",
        "order": 7,
        "difficulty": "Intermediate",
        "isPublished": True,
        "estimated_hours": "30+ hrs",
    },
    {
        "name": "Agentic AI",
        "slug": "agentic-ai",
        "description": "Design autonomous AI agents with ReAct reasoning loops, dynamic tool calling, short/long-term memory, and multi-agent coordination.",
        "icon": "Bot",
        "order": 8,
        "difficulty": "Advanced",
        "isPublished": True,
        "estimated_hours": "35+ hrs",
    },
    {
        "name": "Deep Learning",
        "slug": "deep-learning",
        "description": "Dive into perceptrons, multi-layer neural networks, non-linear activation functions, backpropagation with the chain rule, and modern optimizers.",
        "icon": "Cpu",
        "order": 9,
        "difficulty": "Intermediate to Advanced",
        "isPublished": True,
        "estimated_hours": "35+ hrs",
    },
    {
        "name": "Git & Version Control",
        "slug": "git",
        "description": "Master distributed version control, Git object models (Blobs, Trees, Commits), DAG internals, fast-forward vs 3-way merges, and rebasing.",
        "icon": "GitBranch",
        "order": 10,
        "difficulty": "Beginner to Intermediate",
        "isPublished": True,
        "estimated_hours": "20+ hrs",
    },
    {
        "name": "AWS & Cloud Computing",
        "slug": "aws",
        "description": "Understand cloud foundations, server architectures (IaaS, PaaS, SaaS), Amazon EC2, S3, IAM security, VPC networking, and high availability.",
        "icon": "Cloud",
        "order": 11,
        "difficulty": "Beginner to Advanced",
        "isPublished": True,
        "estimated_hours": "35+ hrs",
    },
]

